### ISSUE TITLE
DemoURL hotels.hc-demos.com is not accessible

### ISSUE THREAD

**Issue by tmkasun** [hopper/hc-hotels-demo#9]
Hi team,

The demo URL given in the GitHub repo details section is not accessible.

![image](https://github.com/hopper/hc-hotels-demo/assets/3313885/4adef628-8cc0-470c-ab8f-16b8a835f4bf)

But I could access the [Simple Example](https://hotels-demo.cloud.hopper.com/plain/) in the Readme.md. You might need to update the URL given in the repo details.

**Comment by crengifohopper** [comment]
thanks for letting us know. url has been updated
